### PR TITLE
Additional feedback

### PR DESCRIPTION
**Pull request by Kelketek**
Forward-ports the additional feedback and extended feedback features.

### CODE REVIEW

**Comment by e-kolpakov** [comment]
@Kelketek I'm afraid I'm not sure how to verify this: how do I enable extended feedback and set assessment review message?

**Comment by Kelketek** [comment]
@e-kolpakov You know... It's only just now occurred to me that I didn't make a front-end way to set extended feedback. I feel silly.

**Comment by e-kolpakov** [comment]
@Kelketek it happens :)

**Comment by Kelketek** [comment]
@e-kolpakov Looks like it'll be easy to add. Give me a few minutes and I'll push an update that should allow you to set these.

**Comment by e-kolpakov** [comment]
@Kelketek there's a problem with "Message (On Assessment Review)"

mcq-editor-buttons

**Comment by e-kolpakov** [comment]
@Kelketek :+1:

**Pull request merged**
