### PR TITLE
[BB-276] move the test logic from circle.yml to tox

### PR DESCRIPTION
**Pull request by dupainaulevain**
No attempt was made to run tests in parallel since the CircleCI features cannot be reproduced with tox alone. As a result the run time of the tests went from [~ 5min](https://circleci.com/gh/open-craft/problem-builder/774?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) to [~ 15min](https://circleci.com/gh/open-craft/problem-builder/780?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

The advantage is that tests can be run locally with the same command that is used in CircleCI which is convenient to reproduce problems and debug them. 

- [x] partial compliance with [OEP-0018](https://open-edx-proposals.readthedocs.io/en/latest/oep-0018-bp-python-dependencies.html) for tests only, reworking the package dependencies would require more work
- [x] clarify the conflicting XBlock requirement (0.4 & 1.2.2) and why the pip install order matter **consolidating all requirements in one file**
- [x] upgrade from pep8 to pycodestyle
- [x] upgrade pylint
- [x] why is xblock-sdk pinned to a given version? would it work otherwise? **is works up to v0.1.4 but fails on master**
- [x] why is problem-builder installed from sources in the dependencies? **no reason**

### CODE REVIEW

**Comment by dupainaulevain** [comment]
@jcdyer gentle ping?

**Comment by jcdyer** [comment]
Thanks for the ping.  I lost track of this in the excitement of the conference.  I'll take a look now.

**Comment by jcdyer** [comment]
I'm trying to follow the installation instructions, and I got an error that pytest isn't installed via selenium_tests in the xblock-sdk directories. For example:

```
======================================================================
ERROR: problem_builder.tests.integration.test_instructor_tool (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: problem_builder.tests.integration.test_instructor_tool
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib64/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/cliff/work/opencraft/src/problem-builder/problem_builder/tests/integration/test_instructor_tool.py", line 9, in <module>
    from xblockutils.base_test import SeleniumXBlockTest
  File "/home/cliff/work/opencraft/src/problem-builder/.tox/py27-django111/lib/python2.7/site-packages/xblockutils/base_test.py", line 29, in <module>
    from workbench.test.selenium_test import SeleniumTest
  File "/home/cliff/work/opencraft/src/problem-builder/xblock-sdk/workbench/test/selenium_test.py", line 7, in <module>
    import pytest
ImportError: No module named pytest
```

**Comment by jcdyer** [comment]
Adding `pytest==4.4.0` to test_requirements.txt seems to help.  Tests are still running, though.

**Comment by dupainaulevain** [comment]
Right, the instructions to run the tests locally were incomplete already and I did not fix them. They still require some guessing (you need tox installed etc.). Only I changed the hints to match with the changes in circle.yml. The problem with fixing the instructions to run the tests is that it depends on the operating system and there are significant variance: I'm not sure how to do that properly. 

Now... the pytest missing you got is really weird because, AFAICT, there is no dependency on pytest at all. Just to be sure I re-ran the tests locally with

```
$ rm -fr .tox ; PATH=/opt/firefox-38.0.5/firefox:$PATH tox -e py27-django111
py27-django111 create: /home/loic/software/opencraft/problem-builder/.tox/py27-django111
py27-django111 installdeps: Django>=1.11,<2.0, -exblock-sdk, -rtest_requirements.txt
py27-django111 develop-inst: /home/loic/software/opencraft/problem-builder
py27-django111 installed: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.,-e git+https://github.com/edx/acid-block.git@e46f9cda8a03e121a00c7e347084d142d22ebfb7#egg=acid_xblock,appdirs==1.4.3,backports.os==0.1.1,binaryornot==0.4.4,bok-choy==0.4.3,browsermob-proxy==0.6.0,certifi==2019.3.9,chardet==3.0.4,cookiecutter==0.9.0,ddt==1.2.1,Django==1.11.20,django-nose==1.4.6,-e git+https://github.com/edx/django-pyfs.git@c94e3f4e3d275b21a41e78852e009128e0fbfdf5#egg=django_pyfs,enum34==1.1.6,fs==2.4.4,funcsigs==1.0.2,future==0.17.1,futures==3.2.0,idna==2.8,Jinja2==2.10,lazy==1.4,lxml==4.3.2,Mako==1.0.8,MarkupSafe==1.1.1,mock==2.0.0,needle==0.3,nose==1.3.7,pbr==5.1.3,Pillow==5.4.1,psutil==2.2.1,pypng==0.0.19,python-dateutil==2.8.0,pytz==2018.9,PyYAML==5.1,requests==2.21.0,selenium==2.47.3,simplejson==3.16.0,six==1.12.0,typing==3.6.6,urllib3==1.24.1,web-fragments==0.3.0,WebOb==1.8.5,XBlock==1.2.2,-e git+git@github.com:open-craft/problem-builder.git@fa0f3b361d2d5e4b8f6f45d7641d6b8c75b6dbff#egg=xblock_problem_builder,-e git+https://github.com/edx/xblock-sdk.git@4b900102d096a977f78de57c804931ad4a4c1ade#egg=xblock_sdk&subdirectory=../../xblock-sdk,xblock-utils==1.2.0
py27-django111 run-test-pre: PYTHONHASHSEED='1016035302'
py27-django111 runtests: commands[0] | xvfb-run --server-args=-ac python run_tests.py problem_builder/v1/tests problem_builder/tests
nosetests problem_builder/v1/tests problem_builder/tests --verbosity=1
Creating test database for alias 'default'...
..../home/loic/software/opencraft/problem-builder/.tox/py27-django111/local/lib/python2.7/site-packages/xblock/runtime.py:578: FutureWarning: IdGenerator will be required in the future in order to support XBlockAsides
  warnings.warn("IdGenerator will be required in the future in order to support XBlockAsides", FutureWarning)
/home/loic/software/opencraft/problem-builder/.tox/py27-django111/local/lib/python2.7/site-packages/xblockutils/resources.py:102: UserWarning: ResourceLoader.render_template has been deprecated in favor of ResourceLoader.render_django_template
  "ResourceLoader.render_template has been deprecated in favor of ResourceLoader.render_django_template"
......
```
I also checked that pytest is not installed at the system level

```
$ type pytest
bash: type: pytest: not found
```
I also looked in the .tox virtualenv looking for pytest magically being installed on my machine.
```
(py27-django111) loic@raise:~/software/opencraft/problem-builder/.tox/py27-django111$ pip freeze
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
-e git+https://github.com/edx/acid-block.git@e46f9cda8a03e121a00c7e347084d142d22ebfb7#egg=acid_xblock
appdirs==1.4.3
backports.os==0.1.1
binaryornot==0.4.4
bok-choy==0.4.3
browsermob-proxy==0.6.0
certifi==2019.3.9
chardet==3.0.4
cookiecutter==0.9.0
ddt==1.2.1
Django==1.11.20
django-nose==1.4.6
-e git+https://github.com/edx/django-pyfs.git@c94e3f4e3d275b21a41e78852e009128e0fbfdf5#egg=django_pyfs
enum34==1.1.6
fs==2.4.4
funcsigs==1.0.2
future==0.17.1
futures==3.2.0
idna==2.8
Jinja2==2.10
lazy==1.4
lxml==4.3.2
Mako==1.0.8
MarkupSafe==1.1.1
mock==2.0.0
needle==0.3
nose==1.3.7
pbr==5.1.3
Pillow==5.4.1
psutil==2.2.1
pypng==0.0.19
python-dateutil==2.8.0
pytz==2018.9
PyYAML==5.1
requests==2.21.0
selenium==2.47.3
simplejson==3.16.0
six==1.12.0
typing==3.6.6
urllib3==1.24.1
web-fragments==0.3.0
WebOb==1.8.5
XBlock==1.2.2
-e git+git@github.com:open-craft/problem-builder.git@fa0f3b361d2d5e4b8f6f45d7641d6b8c75b6dbff#egg=xblock_problem_builder
-e git+https://github.com/edx/xblock-sdk.git@4b900102d096a977f78de57c804931ad4a4c1ade#egg=xblock_sdk&subdirectory=../../xblock-sdk
xblock-utils==1.2.0
```

It looks like we're in the typical **it works for me situation** because of some difficult to find environmental difference. Getting rid of this nuisance is the primary reason why I use docker containers to run tests, both in the CI servers and locally. But going in this direction would be a little bit out of scope.

You can however verify from the [CircleCI output](https://circleci.com/gh/open-craft/problem-builder/786?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) that the tests run there are indeed using tox instead of the previous instructions and they pass as expected.

**Comment by dupainaulevain** [comment]
@jcdyer thanks!

**Pull request merged**
