### PR TITLE
Fix dashboard report image download

### PR DESCRIPTION
**Pull request by omarkhan**
The dashboard report image download can currently fail in 2 different ways:

- If the image is from a different domain and it has been cached by the browser, it won't be converted into a data URL due to cross-domain security issues. A javascript `SecurityError` is thrown, and nothing happens.
- If the image url starts with `//` (no explicit protocol) or the url is relative (e.g. `/static/...`), *and* it hasn't yet been cached by the browser, it will fail to show up in the downloaded report.

This pull request fixes both issues, by:

- Not trying to create a data URL for cross-domain requests
- Expanding relative urls and urls without an explicit protocol

This pull request also extends the integration tests to test report downloads.

### CODE REVIEW

**Comment by Kelketek** [comment]
@omarkhan Test failing here, but it may just need to be rerun.

**Comment by omarkhan** [comment]
@Kelketek the tests are passing now, yay

**Comment by Kelketek** [comment]
:+1:

**Comment by omarkhan** [comment]
@bradenmacdonald do you want to review this one as well?

**Comment by bradenmacdonald** [comment]
@omarkhan Not necessary, thanks. I will review the edx-release hash update PR though.

**Comment by bradenmacdonald** [comment]
@omarkhan Actually never mind I'm not going to review any of these PRs. I was only going to review this master PR if it was a merge from `edx-release` to `master`, which can be tricky`, but you just implemented it separately on each branch so that's fine.

**Comment by omarkhan** [comment]
@bradenmacdonald do I need to get thumbs up from @tobz on this PR as well?

**Comment by bradenmacdonald** [comment]
@omarkhan No, the `master` branch of Problem Builder is maintained by OpenCraft alone. EdX review is only required for the `edx-release` branch.

**Comment by omarkhan** [comment]
@bradenmacdonald thanks that's what I figured, just wanted to make sure before merging

**Pull request merged**
