### PR TITLE
Bump version number.

### PR DESCRIPTION
**Pull request by Kelketek**
@bradenmacdonald Who would we need to review this? It's needed for https://github.com/edx/edx-platform/pull/11312 All it does is bump the version number.

### CODE REVIEW

**Comment by bradenmacdonald** [comment]
:+1: 
It's ok that CircleCI failed since CircleCI is not enabled on this branch.
We should also get a plus 1 from any one of the reviewers on your other PR, then go ahead and merge this.

BTW In future, please don't create the git tag (`v2.0.1`) until after this version bump PR has merged. Then once it has merged, go ahead and tag the merge commit then push the tag. The main reason for this is that tags shouldn't be changed once published (similar to the reason we don't do force pushes to master), and you want to leave yourself some room to fix things in case the version bump PR has an issue.

**Comment by Kelketek** [comment]
@nedbat FYI, version update PR to address the tagging issue for the problem builder hash bump.

**Comment by nedbat** [comment]
I know this is a pain, but TBH I would not count on the moved tag at all.  It's safer to go to 2.0.2.

**Comment by Kelketek** [comment]
@nedbat Very well. I'll update the version again. One moment...

**Comment by Kelketek** [comment]
@nedbat Updated.

**Comment by nedbat** [comment]
:+1:

**Pull request merged**
