### PR TITLE
Test + fix for crash when block is deleted after students have used it

### PR DESCRIPTION
**Pull request by bradenmacdonald**
Forward port of https://github.com/edx-solutions/xblock-mentoring/pull/112

### CODE REVIEW

**Comment by Kelketek** [comment]
@bradenmacdonald Please ping me once you've merged the other task and rebased this atop that so that the tests pass.

**Comment by bradenmacdonald** [comment]
@Kelketek Tests passing now :)

**Comment by smarnach** [comment]
:+1: Code looks good.  While testing this, I managed to mess up my solutions devstack again, and I don't have time this evening to fix it.  Since this PR needs a only a single reviewer anyway, I'll leave the testing to Jonathan.

**Comment by Kelketek** [comment]
:+1: Works for me! Looks good, too.

**Pull request merged**
