### PR TITLE
MCKIN-24633 translation issue for portuguese

### PR DESCRIPTION
**Pull request by mudassir-hafeez**
when we load the instructor tool for portuguese, the following error message shows:
Screenshot 2020-09-21 at 5 56 16 PM

Actually, `segundos` reference is not define and seems like a translation in Portuguese which was used mistakenly. so updating it into an accurate reference.

### CODE REVIEW

**Comment by mudassir-hafeez** [comment]
@xitij2000 failed test does not seem to be related to this PR. Can you please have a look?
Thanks,

**Comment by shimulch** [comment]
@mudassir-hafeez, Thanks for the PR. Re-running circle-ci jobs seem to pass this time.

**Comment by mudassir-hafeez** [comment]
@shimulch can you please review and create a tag against this if code changes seem good?
Same for the PR #302 against master.

**Review by shimulch — APPROVED** [review]
LGTM :+1:

- [x] I tested this: ran tests locally
- [x] I read through the code
~- [ ] I checked for accessibility issues~
~- [ ] Includes documentation~
~- [ ] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.~

**Comment by shimulch** [comment]
Released [v3.5.2](https://github.com/open-craft/problem-builder/releases/tag/v3.5.2)

**Pull request merged**
