### PR TITLE
YONK-1219 - Code optimization for more performance

### PR DESCRIPTION
**Pull request by shafqatfarhan**
Code modified to fetch Tips only once for every MRQ problem inside calculate_results method.

@bradenmacdonald Can you take a look at this PR. 

Ticket link: https://openedx.atlassian.net/browse/YONK-1219

### CODE REVIEW

**Comment by shafqatfarhan** [comment]
@xitij2000 I have made the changes you suggested. Kindly review it. Also, after merging should I make a release from 'problem-builder-v2' branch?

**Comment by xitij2000** [comment]
@shafqatfarhan Thanks for those changes! Sure, you can make the release.

**Comment by shafqatfarhan** [comment]
@xitij2000 It seems like I don't have rights to draft a new release. Can you please make a new release.

**Comment by xitij2000** [comment]
@shafqatfarhan  Done.

**Comment by shafqatfarhan** [comment]
> @shafqatfarhan Done.

Thank you

**Pull request merged**
