### PR TITLE
MCKIN-12152 AF#40-MRQ-Inform assistive technologies of changes in content

### PR DESCRIPTION
**Pull request by nasirhjafri**
MCKIN-12152 AF#40-MRQ-Inform assistive technologies of changes in content

[Issue]
When the submit button is activated, there is new content added to the page without notifying the user through an announcement.  Feedback text appears after the submit button.

[Resolution]
Upon activating the "Submit" button, additional content gets added beneath this button that provides feedback on the response submitted. Upon activating this button, please ensure to set focus to this newly added textual content using the JavaScript focus method, so that assistive technologies such as screen readers would be aware of this content update and would render this content to the screen reader users. Also, place a tabindex of -1 on this dynamically added feedback content container, so that it doesn't appear in the tab order.

### CODE REVIEW

**Comment by nasirhjafri** [comment]
@xitij2000 Please review.

**Comment by xitij2000** [comment]
@nasirhjafri  I've added this to the review backlog, but unfortunately we will probably only be able to get to it next sprint since it wasn't included in the original PR list sent last sprint.

**Comment by Agrendalath** [comment]
@nasirhjafri, please rebase it on the `master` and bump the version in `setup.py`.

**Comment by nasirhjafri** [comment]
@Agrendalath Rebased with the master.

**Comment by lgp171188** [comment]
@nasirhjafri, @Agrendalath, I will review the changes today and post my feedback after that. FYI.

**Comment by lgp171188** [comment]
@nasirhjafri, I tried testing the changes in this PR on the Ironwood devstack. However, I cannot trigger the expected behaviour at all and the element containing the `messages` class is always hidden. So does this require testing on the custom LMS frontend?

**Comment by lgp171188** [comment]
@nasirhjafri, I tested the changes on the custom LMS frontend opened in the Microsoft Edge browser, using the NVDA screen reader on Windows 10 and verified that it works as described. However, when using the built-in screen reader on Windows 10, it didn't work the same way. Since all the screen reader software use the same HTML elements and attributes, I am not sure how and why this happens.

If you have any idea about this, please let me know. Otherwise, this PR looks good to be merged. I will approve after checking your response.

**Comment by nasirhjafri** [comment]
@lgp171188 I don't have an idea about Windows 10 screen reader. We can merge this one as the recommended screen reader is NVDA.

**Comment by lgp171188** [comment]
@nasirhjafri, no problem. I will squash and merge the changes after the CI checks pass and then tag a release and ping you.

**Pull request merged**
