### PR TITLE
update few translations for Arabic

### PR DESCRIPTION
**Pull request by umarmughal824**
Update following translations for Arabic
- Submit -> إرسال
- You have used 1 of 2 submissions -> استهلكت وظيفة "الإرسال" 1 من أصل 2
- You have used 1 of 2 submissions -> استهلكت وظيفة "الإرسال" 2 من أصل 2
- Question (1,2,3,4 etc) > السؤال 1,2,3
- Click a question to review feedback on your response -> انقر على السؤال
للاطلاع على التعليقات المقدّمة على إجابتك   
- You scored % on your assessment -> حصلت على % في تقييمك
- Review Final Grade -> اطّلع على النتيجة النهائية
- Try again -> حاول مرة أخرى

### CODE REVIEW

**Comment by umarmughal824** [comment]
@xitij2000 will you please review this PR?

**Comment by xitij2000** [comment]
@umarmughal824 This is good to merge once a version bump has been included.

**Comment by umarmughal824** [comment]
@xitij2000 version in updated. Please have a look.

**Comment by xitij2000** [comment]
@umarmughal824 Please change the version bump to v3.3.1 instead of v3.4.0 after that this is good to merge.

**Comment by umarmughal824** [comment]
@xitij2000 sure.

**Comment by umarmughal824** [comment]
@xitij2000 do we need release tag for it?

**Comment by xitij2000** [comment]
@umarmughal824 You can see the release tags here: https://github.com/open-craft/problem-builder/releases

**Comment by umarmughal824** [comment]
thanks @xitij2000 already received.

**Pull request merged**
