### PR TITLE
Added notifications for locking navigation on supported platforms.

### PR DESCRIPTION
**Pull request by Kelketek**
Forward ported from V1. Can't be tested until Birch rebase is complete.

### CODE REVIEW

**Comment by bradenmacdonald** [comment]
FYI I am currently rebasing the `develop` branch, so this PR will need to be rebased shortly.

**Comment by bradenmacdonald** [comment]
OK, `develop` branch is rebased.

**Comment by e-kolpakov** [comment]
:+1:

**Comment by Kelketek** [comment]
Closing this PR to remake it against master, since we now have master.

**Comment by Kelketek** [comment]
This PR has moved to https://github.com/open-craft/problem-builder/pull/11

**Pull request closed without merging**
