### PR TITLE
Update all language translations. Including add new languages (Arabic, Spanish, Portuguese, Chinese, French, German and Japanese).

### PR DESCRIPTION
**Pull request by umarmughal824**
Update all language translations. Including add new languages (Arabic, Spanish, Portuguese, Chinese, French, German and Japanese).

### CODE REVIEW

**Comment by umarmughal824** [comment]
@xitij2000 Can you please review it too?

**Comment by xitij2000** [comment]
I see "Next Step" us untranslated. 
screenshot_2018-11-12 step builder overview pb your platform name here

**Comment by xitij2000** [comment]
@umarmughal824 Please rebase this on the latest problem-builder-v2 branch, since the failed test was fixed there long ago.

**Comment by umarmughal824** [comment]
@xitij2000 I recently forked it I guess last week. But still I will rebase it. No worries.

**Comment by umarmughal824** [comment]
@xitij2000 It's updated now.

**Pull request merged**
