### PR TITLE
MCKIN-19254: fix js translations for answer block

### PR DESCRIPTION
**Pull request by msaqib52**
Answer block is not loading js translations due to which following string is not getting translated, This PR includes js translations in answer block response.
pbt

### CODE REVIEW

**Comment by msaqib52** [comment]
@xitij2000 please review this when you have sometime

**Comment by msaqib52** [comment]
@taniwha thank you for the review, could you also merge it and create release tag?

**Comment by xitij2000** [comment]
@msaqib52  Please also crate an equivalent PR against the master branch.

**Comment by msaqib52** [comment]
@xitij2000 have created this PR for v4 https://github.com/open-craft/problem-builder/pull/287

**Comment by taniwha** [comment]
@msaqib52  The merge and release tag (v3.4.19) for this PR were already done, but I'll do the master-PR too.

**Comment by taniwha** [comment]
or, I thought I had, I'll fix

**Comment by taniwha** [comment]
@msaqib52 my appologies

**Comment by msaqib52** [comment]
Thank you @taniwha

**Pull request merged**
