### PR TITLE
update arabic translation for Review Grade

### PR DESCRIPTION
**Pull request by umarmughal824**
Update following translations for Arabic

- Review Grade -> اطّلع على النتيجة

### CODE REVIEW

**Comment by umarmughal824** [comment]
@xitij2000 will you please review this PR?

**Comment by jcdyer** [comment]
:+1:  Looks good to me.  I don't speak arabic, so I'm trusting the content of the translation is accurate.

**Comment by umarmughal824** [comment]
@jcdyer thanks for your response. I have no access for this repository. So I'm merge and create release tag for it. Can you please do that for me?

**Comment by jcdyer** [comment]
A [v3.3.2 tag](https://github.com/open-craft/problem-builder/releases/tag/v3.3.2) has just been published.  You'll need to create a version update PR on edx-platform to put it to use.

**Comment by jcdyer** [comment]
@umarmughal824 Ping me on that PR when it's ready for review.

**Comment by wajeeha-khalid** [comment]
@jcdyer here is platform bump PR https://github.com/edx-solutions/edx-platform/pull/1443
Please review and approve; I will merge once tests pass

**Pull request merged**
