### PR TITLE
MCKIN-13390 Arabic/JA translation for review grade

### PR DESCRIPTION
**Pull request by moeez96**
Jira ticket: https://edx-wiki.atlassian.net/browse/MCKIN-13390

Change translation of `Review grade`:
AR: تصفح الصف
JA: 成績チェッ

### CODE REVIEW

**Comment by moeez96** [comment]
@xitij2000 Please review and tag after merge.

**Comment by lgp171188** [comment]
@moeez96, I tested this on the Ironwood devstack and was able to verify that the updated translations for the `Review grade` text show up correctly in Arabic and Japanese. However, when checking the diff of this PR, the `.mo` files of a few other languages are also changed. Is there a reason why those are changed? If not, can you revert those changes such that only the files related to Arabic and Japanese or changed?

I will approve the PR after I get a clarification from you.

**Comment by moeez96** [comment]
@lgp171188 The .mo files were generated by the i18n tool's command `i18n_tool generate`. It seems like some changes that may have been done previously in .po files were not reflected in .mo files. Hence the tool generated files for all languages.

**Comment by lgp171188** [comment]
@moeez96, since I have no information about the changes in the files for other languages and hence cannot test or verify them, can you discard those changes from this PR? If required, you can create a separate PR with those discarded changes so that they are not missed.

**Comment by moeez96** [comment]
@lgp171188 Done

**Comment by lgp171188** [comment]
@moeez96, :+1: 
- [x] I tested this on the Ironwood devstack and verified that updated translations are displayed correctly
- [x] I read through the code
- [x] ~~I checked for accessibility issues~~ NA
- [x] ~~Includes documentation~~ NA

**Comment by lgp171188** [comment]
@moeez96, I have approved the PR. One final question that I have - the `تصفح الصف` text translates to `Browse the class` when I checked it on Google Translate. Is this the correct translation?

**Comment by moeez96** [comment]
@lgp171188 This was a requirement mentioned in the Jira ticket in description. I take the request was made after confirming from native translators.

**Comment by moeez96** [comment]
@lgp171188 Please merge, and create a release tag. Since I dont have access.

**Comment by lgp171188** [comment]
@moeez96, I have merged this PR and created a release tag `v3.4.11`

**Pull request merged**
