### PR TITLE
MCKIN-19683: fix translations issues

### PR DESCRIPTION
**Pull request by msaqib52**
Some of the strings were not getting translated due to unavailability of translation service in student view. For some strings plural forms were not working due to incorrect translations format, This PR fixes these issues.
Untitled
Untitled (1)
Untitled (2)

@xitij2000 can you review this?

### CODE REVIEW

**Comment by xitij2000** [comment]
@msaqib52 Please make a PR against master as well.

**Comment by msaqib52** [comment]
@xitij2000 i will create PR against master once this PR is reviewed, so that PR against master has reviewed and updated changes. Also could you rerun the `py35-integration` tests, looks like some flaky tests failing.

**Comment by taniwha** [comment]
@msaqib52 The patch looks good to me, but the failed test case is a bit of a concern, so I haven't merged yet. If it proves to be a non-issue, I will merge.

**Comment by taniwha** [comment]
In the end, it passed.

**Comment by xitij2000** [comment]
@msaqib52 Please create a master PR as well now that this is merged.

**Comment by msaqib52** [comment]
@xitij2000 @taniwha have created [this PR](https://github.com/open-craft/problem-builder/pull/289) against master. Could you also create the release tag for v3 merge.

**Comment by taniwha** [comment]
@msaqib52 sorry, I had... sort of. I think I hit the wrong button when I was finished and failed to notice. Sorry. Fixed now.

**Comment by msaqib52** [comment]
@taniwha Thank you.

**Pull request merged**
