### PR TITLE
Fixed comparison mismatch

### PR DESCRIPTION
**Pull request by asadazam93**
### Description
Added empty check on 'min_characters'

**Sandbox**
N/A

### Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] @awaisdar001 

### Post-review
- [ ] Rebase and squash commits

### CODE REVIEW

**Comment by asadazam93** [comment]
@lgp171188 can you please review this PR?

**Comment by lgp171188** [comment]
@asadazam93, @xitij2000 prioritizes and schedules the PRs for review. So I am pinging him.

**Comment by fysheets** [comment]
Hello! Wanted to check in on a potential review here, also to sanity check if we need to have all tests green before a review can be scheduled?

**Comment by asadazam93** [comment]
I noticed that the py27 were failing on previous PRs as well and they were merged anyway. So I am assuming there is an issue with the python2 tests.

**Comment by xitij2000** [comment]
@asadazam93 @fysheets Incredibly sorry for the delay! This slipped under my radar. 

Yes, there are issues with the python2 tests. They seem to be passing locally but failing in the CI. If you find a solution to it that would be lovely, but we can merge this if all tests pass locally, even if they don't here.

**Comment by toxinu** [comment]
@asadazam93 Approved as trivial change. 👍

**Comment by asadazam93** [comment]
@toxinu can you also please merge this PR? I don't have access to merge it

**Comment by toxinu** [comment]
> @toxinu can you also please merge this PR? I don't have access to merge it

I was about to merge it after the version bump but I can do it by myself. Anyway, thanks for your contribution. 👍

**Pull request merged**
