### PR TITLE
MCKIN-12600 key error on filtering username

### PR DESCRIPTION
**Pull request by mudassir-hafeez**
Jira ticket: https://mckinsey.atlassian.net/browse/MEI-6680

Fixed `KeyError: 'student_id'` as it raises when we search username through instructor tool.

### CODE REVIEW

**Comment by mudassir-hafeez** [comment]
@xitij2000 can you please review?

**Comment by xitij2000** [comment]
@mudassir-hafeez  I'm afraid we might not be able to this for the next sprint. We will look into it after mid-april. I hope this is OK?

**Comment by mudassir-hafeez** [comment]
Yup, @xitij2000 thanks for informing! Please take it after mid april.

**Comment by mudassir-hafeez** [comment]
@xitij2000 just a reminder to review. Thanks!

**Review by xitij2000 — APPROVED** [review]
:+1:
- [x] I tested this: tested on master devstack
- [x] I read through the code
- [na] I checked for accessibility issues
- [na] Includes documentation

**Comment by xitij2000** [comment]
@mudassir-hafeez I've tested, approved and merged this and also tagged a release.

**Comment by mudassir-hafeez** [comment]
@xitij2000 thanks for reviewing!

**Pull request merged**
