### PR TITLE
MCKIN-26123 Platform Issues - Translations.

### PR DESCRIPTION
**Pull request by wasifarbisoft**
There are few strings in the problem builder's Assessment that were not getting translated for the polish, Japanese, French, Arabic and Chinese languages. This Pull Request fixed those issues including plural strings.

### CODE REVIEW

**Comment by wasifarbisoft** [comment]
@xitij2000 ,
Please review this PR.
I have also created a parallel PR for the Master branch for python3
https://github.com/open-craft/problem-builder/pull/314

**Review by xitij2000 — APPROVED** [review]
:+1:
- [x] I tested this: tested on solutions devstack.
- [x] I read through the code

**Comment by wasifarbisoft** [comment]
@xitij2000 if all good then it can be merged?

**Comment by wasifarbisoft** [comment]
@xitij2000 Added the description to this pull request.

**Pull request merged**
