### PR TITLE
Minor tweaks to better match the Apros theme

### PR DESCRIPTION
**Pull request by bradenmacdonald**
When the Apros theme is active, this makes the main header (an `h2`) match the color of Apros `<h2 class="main">` headers. It also makes the subheaders use all-caps, as Apros does.

Screenshot:
screen shot 2015-06-12 at 2 34 19 pm

### CODE REVIEW

**Comment by Kelketek** [comment]
@bradenmacdonald These changes look good, but the tests are failing. They don't look like they should be related, but do we know why they are?

**Comment by bradenmacdonald** [comment]
@Kelketek Yeah, I think it's unrelated. I assumed it was the issue[s] that @smarnach was working on, so I didn't look into it too much. @smarnach can you please advise if these failures here are related to something that you're working to fix, or should I investigate them?

**Comment by smarnach** [comment]
@bradenmacdonald These are not issues I've been working on, though I've seen the three test failures with the message `'checkmark-correct' not found` before.  However, I haven't seen the timeout yet.

There were many more test failures which have been fixed by the xblock-sdk PR.  The PR that is still pending is necessary to get the dependencies consistent again, but it won't fix any further tests.

I planned to look into the `'checkmark-correct' not found` issues, but didn't find the time to do so yet, so I wouldn't mind if you could take this on.

**Comment by bradenmacdonald** [comment]
@Kelketek This should be ready now. I got the build passing again, after a lot of frustrating debugging (since the failures only happened on Travis and never locally). Long story short is most of the failures were caused by the test reloading the page and then running tests before the page's JavaScript had finished initializing everything on the page. No idea why those errors were suddenly showing up now and not before.

I also bumped the xblock-utils and xblock versions to match Sven's recent version bump commits in other places.

**Comment by Kelketek** [comment]
@bradenmacdonald :+1: @smarnach Will you be able to rebase upon these changes as soon as @bradenmacdonald finishes them, so that all the builds are green?

**Pull request merged**
