### PR TITLE
MCKIN-25170 Translation correction for Japanese

### PR DESCRIPTION
**Pull request by musmanmalik**
Translation correction for Japanese

### CODE REVIEW

**Review by aayushagra — CHANGES_REQUESTED** [review]
@musmanmalik 

When i try to run compile_messages it exits with the following error:

django-admin.py compilemessages -v0
CommandError: Execution of msgfmt failed: /home/i7/opencraft/extra/problem-builder/conf/locale/ar/LC_MESSAGES/text.po:1554: 'msgstr[1]' is not a valid Python format string, unlike 'msgid_plural'. Reason: The character that terminates the directive number 1 is not a valid conversion specifier.
msgfmt: found 1 fatal error

**Comment by musmanmalik** [comment]
@aayushagra Thanks for highlighting, I have rectified. Please proceed.

**Comment by aayushagra** [comment]
:+1:

- [x] I tested this: I read the code, checked out and ran compile_translations on my local system, checked that all tests pass, installed it on my ironwood devstack and made sure problem-builder still works, changed my language to arabic and japanese and ensured problem-builder still works correctly
- [x] I read through the code
- [x] I checked for accessibility issues
- [ ] Includes documentation
- [ ] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.

**Review by aayushagra — APPROVED** [review]

**Comment by msaqib52** [comment]
@aayushagra it seems like that you have created release https://github.com/open-craft/problem-builder/tree/v3.5.5 from `master` while it should have been from `problem-builder-v3` branch, Can you please fix it.

cc: @xitij2000 @musmanmalik

**Comment by aayushagra** [comment]
@msaqib52  Yep thanks for catching this, fixed!

**Pull request merged**
