### PR TITLE
RTL feedback for problem Builder

### PR DESCRIPTION
**Pull request by murad-hubib**
- Fixed feedback position in RTL
- updated version

### CODE REVIEW

**Comment by murad-hubib** [comment]
@mtyaka Can you please review this PR? 

**Steps to see the changes**:
1- Select "Mentoring Default"
2- Make selection of MCQ & MRQ and Submit
3- Feeback and Tips should be on left

**Note**: _This is a RTL fix so please make sure you perform these steps in RTL environment_

**Comment by bradenmacdonald** [comment]
@xitij2000 FYI

**Comment by murad-hubib** [comment]
@bradenmacdonald Do we have any progress on this review?

CC: @xitij2000

**Comment by xitij2000** [comment]
Hi @murad-hubib! It's been scheduled for the current sprint, so should be reviewed this week.

**Comment by mtyaka** [comment]
Thanks @murad-hubib!

:+1:

- [x] I tested this: Verified the feedback popups look good in RTL mode in LMS and apros.
- [x] I read through the code
- [x] I checked for accessibility issues
- [ ] ~~Includes documentation~~ n/a

**Pull request merged**
