### PR TITLE
MCKIN-8751: Add markers to set completion criteria.

### PR DESCRIPTION
**Pull request by jcdyer**
MCKIN-8751

In addition to the mentioned block, it looks like some others may not have been configured properly.

Open question: should answer recap be excluded or complete-on-view?

### CODE REVIEW

**Comment by xitij2000** [comment]
@jcdyer There seems to be a failing test, could you look into that?

**Comment by jcdyer** [comment]
@xitij2000 Will do.  It looks unrelated, but I'll investigate.

**Comment by jcdyer** [comment]
@xitij2000 Looks like the same thing @lgp171188 just ran into and fixed.  I'm cherry picking his fix.

**Comment by jcdyer** [comment]
Tests passed, RFR.

**Comment by xitij2000** [comment]
@jcdyer Could you cherry pick this to master as well?

**Pull request merged**
