### PR TITLE
Add Portuguese (Portugal) translation

### PR DESCRIPTION
**Pull request by MoisesGSalas**
### Description
Add Portuguese of Portugal translations.

### CODE REVIEW

**Comment by arbrandes** [comment]
@MoisesGSalas, many thanks for the contribution!  We'll get to reviewing it ASAP!

**Comment by swalladge** [comment]
@arbrandes do we have an internal ticket created to track reviewing this and https://github.com/open-craft/xblock-poll/pull/94 ?

**Comment by arbrandes** [comment]
@swalladge, no, but I did ask for takers [in the forum](https://forum.opencraft.com/t/incoming-contribution-to-problem-builder/1056).  A proper review of the translation itself is, AFAIK, limited to either me, @giovannicimolin, @viadanna, or @jvdm, though.  Any of you interested?

**Comment by jvdm** [comment]
@swalladge and @arbrandes: I can take it.

**Comment by arbrandes** [comment]
@jvdm, awesome, thanks!

**Comment by giovannicimolin** [comment]
@jvdm I have some CC time this sprint, do you want me to take this up?

**Comment by jvdm** [comment]
@giovannicimolin Absolutely, please go ahead.

**Comment by giovannicimolin** [comment]
@MoisesGSalas Look good! I just need a version bump [here](https://github.com/open-craft/problem-builder/blob/master/setup.py#L31) to push this forward and create a release. `4.1.14` is ok - we're just pulling a new translation.

@arbrandes Btw, this is now about reviewing the translations, but the translation support and check that it's pulling the correct language. The translations are the approved ones on transifex (https://www.transifex.com/open-edx/xblocks/problem-builder/)

**Comment by MoisesGSalas** [comment]
@giovannicimolin Done. Seems like we have been getting used to each other this last month.

The tests failed, seems to be due to the new Debian release that happened last week. I will hear you on how to proceed on this.

**Comment by giovannicimolin** [comment]
We're working on it on a related pull request. I'll get back to you once we have news.

**Comment by Agrendalath** [comment]
I cannot rebase this branch through GitHub, so I'll close it for now. Please reopen if it's still relevant.

**Pull request closed without merging**
