### PR TITLE
MCKIN-22514 round off correctly for v3

### PR DESCRIPTION
**Pull request by mudassir-hafeez**
Jira ticket https://edx-wiki.atlassian.net/browse/MCKIN-22514

There is an endpoint that was missed in #267 which needs to be addressed.

### CODE REVIEW

**Comment by mudassir-hafeez** [comment]
@xitij2000 here is the PR for v3. Can you please review it?

**Review by aayushagra — APPROVED** [review]
Good to go

**Comment by mudassir-hafeez** [comment]
Thank you @aayushagra for reviewing this PR. we have the same #296  for the master branch. Can you please review that too?

**Comment by aayushagra** [comment]
:+1:

- [x] I tested this: Tested that changes work and all tests pass
- [x] I read through the code
- [ ] I checked for accessibility issues
- [ ] Includes documentation
- [ ] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.

**Comment by mudassir-hafeez** [comment]
@aayushagra It seems like you didn't create the release tag version as it should be. I think it would be a typo and should be `v3.4.23` prefix semantic version with “v” rather than this `3.4.23`, and same for 4.0.7

**Comment by xitij2000** [comment]
@mudassir-hafeez I've updated the tags. We've been a bit inconsistent about this at times.

**Comment by mudassir-hafeez** [comment]
@xitij2000 thank you for updating the tags.

**Pull request merged**
