### PR TITLE
MCKIN-12576 Stopped videos while moving to next step

### PR DESCRIPTION
**Pull request by nasirhjafri**
MCKIN-12576 Stopped videos while moving to the next step

If there is more than one step in assessment and we play a video, the video keeps playing in the background when we move to the next step.

### CODE REVIEW

**Comment by nasirhjafri** [comment]
@xitij2000 Please review it.

**Comment by xitij2000** [comment]
@nasirhjafri Sure. I've put it in for review next sprint. 

That said I think this approach is too specific and only works for one specific type of video player. I think you should make it more generic so it works with other kinds of video embeds as well. You can do so  you can do so by using the underlying HTML video player API. i.e. find all HTML5 video elements and pause them.

**Comment by nasirhjafri** [comment]
@xitij2000 Thanks, I've pushed the recommended changes. Please review it in the next sprint.

**Comment by nasirhjafri** [comment]
Thanks, @xitij2000 for reviewing.

**Pull request merged**
